/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCatalogueRouteImport } from './routes/_app/catalogue'
import { Route as AppCatalogueSizesRouteImport } from './routes/_app/catalogue/sizes'
import { Route as AppCatalogueSeriesRouteImport } from './routes/_app/catalogue/series'
import { Route as AppCatalogueFinishesRouteImport } from './routes/_app/catalogue/finishes'
import { Route as AppCatalogueDesignsRouteImport } from './routes/_app/catalogue/designs'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueSizesRoute = AppCatalogueSizesRouteImport.update({
  id: '/sizes',
  path: '/sizes',
  getParentRoute: () => AppCatalogueRoute,
} as any)
const AppCatalogueSeriesRoute = AppCatalogueSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppCatalogueRoute,
} as any)
const AppCatalogueFinishesRoute = AppCatalogueFinishesRouteImport.update({
  id: '/finishes',
  path: '/finishes',
  getParentRoute: () => AppCatalogueRoute,
} as any)
const AppCatalogueDesignsRoute = AppCatalogueDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AppCatalogueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/catalogue': typeof AppCatalogueRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/catalogue/designs': typeof AppCatalogueDesignsRoute
  '/catalogue/finishes': typeof AppCatalogueFinishesRoute
  '/catalogue/series': typeof AppCatalogueSeriesRoute
  '/catalogue/sizes': typeof AppCatalogueSizesRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/catalogue': typeof AppCatalogueRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/catalogue/designs': typeof AppCatalogueDesignsRoute
  '/catalogue/finishes': typeof AppCatalogueFinishesRoute
  '/catalogue/series': typeof AppCatalogueSeriesRoute
  '/catalogue/sizes': typeof AppCatalogueSizesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/catalogue': typeof AppCatalogueRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/catalogue/designs': typeof AppCatalogueDesignsRoute
  '/_app/catalogue/finishes': typeof AppCatalogueFinishesRoute
  '/_app/catalogue/series': typeof AppCatalogueSeriesRoute
  '/_app/catalogue/sizes': typeof AppCatalogueSizesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/catalogue/designs'
    | '/catalogue/finishes'
    | '/catalogue/series'
    | '/catalogue/sizes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/catalogue/designs'
    | '/catalogue/finishes'
    | '/catalogue/series'
    | '/catalogue/sizes'
  id:
    | '__root__'
    | '/_app'
    | '/_app/catalogue'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/orders'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/catalogue/designs'
    | '/_app/catalogue/finishes'
    | '/_app/catalogue/series'
    | '/_app/catalogue/sizes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue': {
      id: '/_app/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue/sizes': {
      id: '/_app/catalogue/sizes'
      path: '/sizes'
      fullPath: '/catalogue/sizes'
      preLoaderRoute: typeof AppCatalogueSizesRouteImport
      parentRoute: typeof AppCatalogueRoute
    }
    '/_app/catalogue/series': {
      id: '/_app/catalogue/series'
      path: '/series'
      fullPath: '/catalogue/series'
      preLoaderRoute: typeof AppCatalogueSeriesRouteImport
      parentRoute: typeof AppCatalogueRoute
    }
    '/_app/catalogue/finishes': {
      id: '/_app/catalogue/finishes'
      path: '/finishes'
      fullPath: '/catalogue/finishes'
      preLoaderRoute: typeof AppCatalogueFinishesRouteImport
      parentRoute: typeof AppCatalogueRoute
    }
    '/_app/catalogue/designs': {
      id: '/_app/catalogue/designs'
      path: '/designs'
      fullPath: '/catalogue/designs'
      preLoaderRoute: typeof AppCatalogueDesignsRouteImport
      parentRoute: typeof AppCatalogueRoute
    }
  }
}

interface AppCatalogueRouteChildren {
  AppCatalogueDesignsRoute: typeof AppCatalogueDesignsRoute
  AppCatalogueFinishesRoute: typeof AppCatalogueFinishesRoute
  AppCatalogueSeriesRoute: typeof AppCatalogueSeriesRoute
  AppCatalogueSizesRoute: typeof AppCatalogueSizesRoute
}

const AppCatalogueRouteChildren: AppCatalogueRouteChildren = {
  AppCatalogueDesignsRoute: AppCatalogueDesignsRoute,
  AppCatalogueFinishesRoute: AppCatalogueFinishesRoute,
  AppCatalogueSeriesRoute: AppCatalogueSeriesRoute,
  AppCatalogueSizesRoute: AppCatalogueSizesRoute,
}

const AppCatalogueRouteWithChildren = AppCatalogueRoute._addFileChildren(
  AppCatalogueRouteChildren,
)

interface AppRouteChildren {
  AppCatalogueRoute: typeof AppCatalogueRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogueRoute: AppCatalogueRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
